language: node_js
node_js:
  - "lts/*"
  - "node"
before_script:
  - npm run tslint-check
script:
  - npm run lint:ci
  - npm run build:all
  - npm run cypress:ci
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "node"
